// Initial catalog, taken from "reporte ventas.xlsx". Prices start at 0 and are set in the app.
const SEED_CATEGORIES = [
  'Pizzas',
  'Bocaditos',
  'Fritas y picadera',
  'Espaguetis',
  'Café',
  'Helados',
  'Bebidas',
  'Dulces',
];

const SEED_PRODUCTS = [
  ['Pizza de queso caribe', 'Pizzas'],
  ['Pizza de queso caribe y jamón', 'Pizzas'],
  ['Pizza de queso Gouda', 'Pizzas'],
  ['Pizza de queso Gouda y jamón', 'Pizzas'],
  ['Pizza especial', 'Pizzas'],
  ['Bocadito de queso', 'Bocaditos'],
  ['Bocadito de jamón y queso', 'Bocaditos'],
  ['Fritas de plátano', 'Fritas y picadera'],
  ['Fritas de malanga', 'Fritas y picadera'],
  ['Chicharrón', 'Fritas y picadera'],
  ['Dados de queso', 'Fritas y picadera'],
  ['Dados de jamón', 'Fritas y picadera'],
  ['Dados de jamón y queso', 'Fritas y picadera'],
  ['Espaguetis de queso', 'Espaguetis'],
  ['Espaguetis de jamón y queso', 'Espaguetis'],
  ['Café expreso', 'Café'],
  ['Café bombón', 'Café'],
  ['Café capuchino', 'Café'],
  ['Café frapuchino', 'Café'],
  ['Pote de helado', 'Helados'],
  ['Helado Piny', 'Helados'],
  ['Barquillo', 'Helados'],
  ['Barquillo de helado', 'Helados'],
  ['Vaso grande', 'Bebidas'],
  ['Vaso chiquito', 'Bebidas'],
  ['Vaso de cerveza', 'Bebidas'],
  ['Jarro de 3 litros', 'Bebidas'],
  ['Cerveza importada', 'Bebidas'],
  ['Cerveza nacional', 'Bebidas'],
  ['Shaka', 'Bebidas'],
  ['Refresco de lata', 'Bebidas'],
  ['Malta', 'Bebidas'],
  ['Malteada', 'Bebidas'],
  ['Tres leches', 'Dulces'],
  ['Beso de ángel', 'Dulces'],
  ['Cheesecake', 'Dulces'],
];
